### ISSUE TITLE
Update Portal on Heroku

### ISSUE THREAD

**Issue by brandecho** [proximiio/proximiio-web-portal#1]
Can you please provide instructions to update portal from the npm repository when using Heroku?
Thank you in advance.

**Comment by MikaKoskiola** [comment]
Best way to update the portal instance at the Heroku is to clone our public portal repository under your own GitHub account, link that with the Heroku and use the "Deploy" tab under application management to deploy the forked portal. You can find more information about this from Heroku's docs: https://devcenter.heroku.com/articles/github-integration

Another option is to use local Heroku toolbelt. In this case you can clone / download our public portal repository archive and use that with the tools to update the portal (i.e git push heroku master).

**Comment by brandecho** [comment]
Thank you @MikaKoskiola! That was extremely easy. We went with your first option of deploying the update from the portal repository under our own GitHub account.
